# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb7f00832487b79a67f8742d4e66552d7096aa08aee726dfa276b5447192a6af51037b526a63bffdb9942796c1da0884222fda0f10d2f758e25ed8a12a07f854

test:
  secret_key_base: 5a5d0c365ca1363bb29f2ace5952de99b144ebff9a5ac2dc38b68ac5d148753979c7e99e9738bedd8df89f8e99ccbe9708102a4d1c60a9395e8502bcc4679653

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
